name: My 1st Workflow
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "NAJIB"